# Generated by Django 4.2.11 on 2024-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='key',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
